#!/bin/bash

echo "🔍 Checking Firebase Auth Configuration"
echo "======================================"
echo ""

echo "1. CHECK OAUTH CONSENT SCREEN"
echo "----------------------------"
echo "Go to: https://console.cloud.google.com/apis/credentials/consent?project=kbe-website"
echo ""
echo "Make sure:"
echo "- Publishing status is 'In production' (not Testing)"
echo "- User type is 'External'"
echo "- Authorized domains include:"
echo "  • kbe-website.firebaseapp.com"
echo "  • homerconnect.com"
echo "  • kbe-website--kbe-website.us-central1.hosted.app"
echo ""

echo "2. CHECK AUTHORIZED DOMAINS IN FIREBASE"
echo "--------------------------------------"
echo "Go to: https://console.firebase.google.com/project/kbe-website/authentication/settings"
echo ""
echo "Under 'Authorized domains', make sure these are listed:"
echo "- localhost"
echo "- kbe-website.firebaseapp.com"
echo "- kbe-website--kbe-website.us-central1.hosted.app"
echo "- homerconnect.com"
echo ""

echo "3. CHECK GOOGLE PROVIDER SETTINGS"
echo "--------------------------------"
echo "Go to: https://console.firebase.google.com/project/kbe-website/authentication/providers"
echo ""
echo "Click on Google provider and ensure:"
echo "- It's enabled"
echo "- Web SDK configuration has client ID"
echo ""

echo "4. CHECK API SERVICES"
echo "--------------------"
echo "Go to: https://console.cloud.google.com/apis/library?project=kbe-website"
echo ""
echo "Make sure these APIs are ENABLED:"
echo "- Identity Toolkit API"
echo "- Firebase Authentication API"
echo "- Google Identity Toolkit API"
echo ""

echo "5. CURRENT FIREBASE CONFIG"
echo "-------------------------"
echo "API Key: AIzaSyBhTEs3Uxq_KBLBzbzIL2VB4Ao_DBw9faM"
echo "Auth Domain: kbe-website.firebaseapp.com"
echo "Project ID: kbe-website"
echo ""

echo "6. TEST WITH CURL"
echo "-----------------"
echo "Testing if the API key works at all:"
echo ""
curl -X POST "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=AIzaSyBhTEs3Uxq_KBLBzbzIL2VB4Ao_DBw9faM" \
  -H "Content-Type: application/json" \
  -d '{"returnSecureToken":true}' 2>&1 | grep -E "(error|message|kind)"

echo ""
echo ""
echo "If you see 'MISSING_EMAIL' error above, the API key is working!"
echo "If you see 'API key not valid' or similar, there's a deeper issue."