#!/bin/bash

echo "🔧 Fixing homerconnect.com Domain Connection"
echo "=========================================="
echo ""

echo "Current Status:"
echo "--------------"
echo "✓ App is deployed to: Firebase App Hosting (kbe-website backend)"
echo "✗ Domain points to: Firebase Hosting (empty site)"
echo ""

echo "The Problem:"
echo "-----------"
echo "Your firebase.json has a 'hosting' section that created a separate"
echo "Firebase Hosting site, but your Next.js app is on App Hosting."
echo ""

echo "Step 1: Remove the domain from Firebase Hosting"
echo "----------------------------------------------"
echo "Run this command to list current Hosting sites:"
echo ""
echo "firebase hosting:sites:list"
echo ""
echo "Then remove the domain from the homerconnect site:"
echo "firebase hosting:sites:delete homerconnect"
echo ""

echo "Step 2: Check your App Hosting backend"
echo "-------------------------------------"
echo "firebase apphosting:backends:list"
echo ""

echo "Step 3: Add domain to App Hosting via Console"
echo "--------------------------------------------"
echo "Since CLI doesn't support App Hosting domains yet:"
echo ""
echo "1. Go to: https://console.firebase.google.com/project/kbe-website/apphosting"
echo "2. Click on 'kbe-website' backend"
echo "3. Click 'Settings' or 'Domains' tab"
echo "4. Click 'Add custom domain'"
echo "5. Enter: homerconnect.com"
echo "6. Follow the DNS instructions provided"
echo ""

echo "Step 4: Update DNS Records"
echo "-------------------------"
echo "Firebase App Hosting will give you new DNS records."
echo "They will likely be different from current ones:"
echo ""
echo "Current (incorrect) records pointing to Hosting:"
echo "A @ 151.101.1.195"
echo "A @ 151.101.65.195"
echo ""
echo "You'll need to update to App Hosting IPs (example):"
echo "A @ 35.219.200.11"
echo "TXT @ [verification-token]"
echo ""

echo "Step 5: Fix API Key Restrictions"
echo "--------------------------------"
echo "While DNS propagates, fix the API key:"
echo ""
echo "1. Go to: https://console.cloud.google.com/apis/credentials?project=kbe-website"
echo "2. Edit the Browser API key (AIzaSyBhTEs3Uxq_KBLBzbzIL2VB4Ao_DBw9faM)"
echo "3. Under 'Application restrictions', temporarily set to 'None'"
echo "4. Save and wait 5 minutes"
echo "5. After testing works, add HTTP referrers:"
echo "   - https://homerconnect.com/*"
echo "   - https://www.homerconnect.com/*"
echo "   - https://kbe-website--kbe-website.us-central1.hosted.app/*"
echo ""

echo "Current DNS Status:"
echo "------------------"
dig homerconnect.com A +short

echo ""
echo "App Hosting URL (working):"
echo "-------------------------"
echo "https://kbe-website--kbe-website.us-central1.hosted.app"
echo ""

echo "To test if API key is fixed:"
echo "---------------------------"
echo "1. Open incognito window"
echo "2. Go to the App Hosting URL above"
echo "3. Try to sign in"
echo "4. If it works, the API key is fixed"
echo ""

echo "Need help? Check Firebase App Hosting docs:"
echo "https://firebase.google.com/docs/app-hosting"