#!/bin/bash

echo "🔍 Diagnosing Firebase Auth API Blocking Issue"
echo "============================================="
echo ""

echo "Error: auth/requests-to-this-api-identitytoolkit-method-are-blocked"
echo "This means your Firebase API key has restrictions blocking homerconnect.com"
echo ""

echo "📋 Current Configuration:"
echo ""

# Get the API key from env
if [ -f .env.local ]; then
    API_KEY=$(grep NEXT_PUBLIC_FIREBASE_API_KEY .env.local | cut -d '=' -f2)
    echo "API Key: ${API_KEY:0:10}..."
else
    echo "❌ .env.local not found"
fi

echo ""
echo "🔧 How to Fix:"
echo ""

echo "Option 1: Update API Key Restrictions (Recommended)"
echo "=================================================="
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/apis/credentials?project=kbe-website"
echo ""
echo "2. Find your Browser API key (usually named 'Browser key (auto created by Firebase)')"
echo "   - Look for key starting with: AIzaSyCQ..."
echo ""
echo "3. Click on the API key to edit"
echo ""
echo "4. Under 'Application restrictions':"
echo "   - Select 'HTTP referrers (websites)'"
echo "   - Add these referrers:"
echo "     • https://homerconnect.com/*"
echo "     • https://www.homerconnect.com/*"
echo "     • https://kbe-website.firebaseapp.com/*"
echo "     • https://kbe-website.web.app/*"
echo "     • http://localhost:*/*"
echo "     • http://localhost:9002/*"
echo ""
echo "5. Under 'API restrictions':"
echo "   - Either select 'Don't restrict key' (easier)"
echo "   - OR select 'Restrict key' and enable:"
echo "     • Identity Toolkit API"
echo "     • Firebase Installations API"
echo "     • Token Service API"
echo ""
echo "6. Click 'Save'"
echo ""

echo "Option 2: Create New Unrestricted API Key (Quick Fix)"
echo "===================================================="
echo "1. Go to: https://console.cloud.google.com/apis/credentials?project=kbe-website"
echo "2. Click '+ CREATE CREDENTIALS' → 'API key'"
echo "3. Copy the new API key"
echo "4. Update .env.local with new key"
echo "5. Restart dev server"
echo ""

echo "Option 3: Check Firebase Project Settings"
echo "========================================"
echo "1. Go to: https://console.firebase.google.com/project/kbe-website/settings/general"
echo "2. Scroll to 'Your apps' → Web app"
echo "3. Verify the API key matches your .env.local"
echo ""

echo "🔍 SSL Certificate Issue:"
echo "========================"
echo "If SSL still shows as insecure:"
echo ""
echo "1. Check Cloudflare SSL/TLS settings:"
echo "   - Must be set to 'Full' or 'Full (strict)'"
echo "   - NOT 'Flexible' or 'Off'"
echo ""
echo "2. Check if Cloudflare proxy is enabled:"
echo "   - Orange cloud = Proxied (might cause issues during setup)"
echo "   - Gray cloud = DNS only (recommended during setup)"
echo ""
echo "3. Wait for propagation:"
echo "   - SSL certificates can take up to 24 hours"
echo "   - Check status at: https://console.firebase.google.com/project/kbe-website/hosting/sites"
echo ""

echo "📝 Quick Debug Commands:"
echo ""
echo "# Check current DNS"
echo "dig homerconnect.com +short"
echo ""
echo "# Check SSL certificate"
echo "openssl s_client -connect homerconnect.com:443 -servername homerconnect.com < /dev/null 2>/dev/null | openssl x509 -noout -subject -issuer"
echo ""
echo "# Test API key directly"
echo "curl -X POST 'https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key='$API_KEY \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Referer: https://homerconnect.com' \\"
echo "  -d '{\"requestType\":\"EMAIL_SIGNIN\",\"email\":\"test@example.com\",\"continueUrl\":\"https://homerconnect.com\"}'"
echo ""