#!/bin/bash

echo "🔧 Fix DNS and API Key Issues"
echo "============================="
echo ""

echo "1. DNS RECORDS ISSUE"
echo "-------------------"
echo "You have 3 A records, but only 1 should exist:"
echo ""
echo "❌ DELETE these old Firebase Hosting records:"
echo "   A @ 151.101.65.195"
echo "   A @ 151.101.1.195"
echo ""
echo "✅ KEEP only this App Hosting record:"
echo "   A @ 35.219.200.11"
echo ""
echo "Go to Cloudflare and delete the two 151.101.x.x records NOW."
echo ""

echo "2. API KEY RESTRICTIONS"
echo "----------------------"
echo "The API key needs to allow your App Hosting URL."
echo ""
echo "Go to: https://console.cloud.google.com/apis/credentials?project=kbe-website"
echo ""
echo "Edit the Browser API key (AIzaSyBhTEs3Uxq_KBLBzbzIL2VB4Ao_DBw9faM)"
echo ""
echo "Under 'Application restrictions':"
echo "- Keep it as 'HTTP referrers'"
echo "- Add these referrers:"
echo "  • https://kbe-website--kbe-website.us-central1.hosted.app/*"
echo "  • https://homerenrichment.com/*"
echo "  • https://www.homerenrichment.com/*"
echo "  • http://localhost:*"
echo "  • http://localhost:9002/*"
echo ""
echo "Make sure to include the /* at the end!"
echo ""

echo "3. CURRENT DNS STATUS"
echo "--------------------"
dig homerenrichment.com A +short

echo ""
echo "4. TEST AUTHENTICATION"
echo "---------------------"
echo "After fixing DNS and API key, test at:"
echo "1. https://kbe-website--kbe-website.us-central1.hosted.app (should work immediately)"
echo "2. https://homerenrichment.com (after DNS propagates)"
echo ""

echo "5. CHECK API KEY STATUS"
echo "-----------------------"
echo "To verify API key is working, open browser console and check for errors."
echo "The auth/requests-to-this-api error means the referrer isn't allowed."