#!/bin/bash

echo "🌐 Setting up homerconnect.com for KBE Website"
echo "============================================="

echo ""
echo "📋 Current Setup Status:"
echo ""

# Check current sites
echo "1. Firebase Hosting Sites:"
firebase hosting:sites:list

echo ""
echo "🔧 Manual Steps Required:"
echo ""
echo "1. Add Custom Domain in Firebase Console:"
echo "   • Go to: https://console.firebase.google.com/project/kbe-website/hosting/sites"
echo "   • Click on 'homerconnect' site"
echo "   • Click 'Add custom domain'"
echo "   • Enter: homerconnect.com"
echo ""
echo "2. Configure Cloudflare DNS (IMPORTANT):"
echo "   • Go to Cloudflare Dashboard for homerconnect.com"
echo "   • Add these DNS records:"
echo ""
echo "   Type: A"
echo "   Name: @ (or homerconnect.com)"
echo "   Value: 151.101.1.195"
echo "   Proxy: DNS only (gray cloud) ⚠️"
echo ""
echo "   Type: A"
echo "   Name: @ (or homerconnect.com)"
echo "   Value: 151.101.65.195"
echo "   Proxy: DNS only (gray cloud) ⚠️"
echo ""
echo "3. Update Cloudflare SSL/TLS Settings:"
echo "   • Go to SSL/TLS → Overview"
echo "   • Set to: Full (strict)"
echo "   • NOT Flexible (causes redirect loops)"
echo ""
echo "4. Add to Firebase Auth Authorized Domains:"
echo "   • Go to: https://console.firebase.google.com/project/kbe-website/authentication/settings"
echo "   • Add: homerconnect.com"
echo "   • Add: www.homerconnect.com (optional)"
echo ""
echo "5. Update Environment Variables:"
echo "   Add to .env.local:"
echo "   NEXT_PUBLIC_APP_URL=https://homerconnect.com"
echo "   NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=homerconnect.com"
echo ""
echo "⏱️  Timeline:"
echo "   • DNS: 5 minutes to 48 hours"
echo "   • SSL: Up to 24 hours"
echo "   • Auth: Works immediately after domain authorized"
echo ""
echo "🔍 To check domain status:"
echo "   firebase hosting:sites:get homerconnect"
echo ""