name: Test Suite

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'
      - 'test/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with debug logging'
        required: false
        default: false

permissions:
  contents: read

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Quick Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.21'

      - name: Install Dependencies
        run: bun ci

      - name: Type Check (non-blocking)
        run: bun run typecheck
        continue-on-error: true

      - name: Run Tests (informational)
        run: bun run test:ci
        env:
          CI: true
        continue-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage/
            test-results/
